### ISSUE TITLE
Keeps crashing

### ISSUE THREAD

**Issue by Em1b0r** [AmyMialeeCommissions/annoyingdifficulty#1]
![image](https://github.com/AmyMialeeCommissions/annoyingdifficulty/assets/147840874/8e7bca69-654c-4abd-9c59-46ef6f617374)
it keeps giving me this crash

**Comment by AmyMialee** [comment]
are you on the 1.0.1?

**Comment by AmyMialee** [comment]
and when does it happen

**Comment by Em1b0r** [comment]
it has happened twice, once when i got too many ads and once when i killed a pig

**Comment by AmyMialee** [comment]
again what version of the mod are you using

**Comment by Em1b0r** [comment]
1.0.1

**Comment by AmyMialee** [comment]
this issue is impossible on the latest build, the mod only uses minecraft's random for the doors and water buckets

**Comment by neamm** [comment]
Also happens with me while I am on 1.0.1

**Comment by AmyMialee** [comment]
yeah try 1.0.2 once it's out
i'm going to close this assuming it's fixed, feel free to reopen or make a new issue if you get it in 1.0.2
