### ISSUE TITLE
Weight System Crashing The Game

### ISSUE THREAD

**Issue by altek3** [AmyMialeeCommissions/annoyingdifficulty#10]
![Screenshot 2023-10-13 194604](https://github.com/AmyMialeeCommissions/annoyingdifficulty/assets/58648258/f5adbc75-38d1-4a39-828b-e344acf8a189)
Everything works fine until I pick up any item or block which leads the game to instantly crash. I assume it is the weight system not working properly with me or even it not being their (It does not show the weight in inventory).

I have fabric-1.20.1, Geckolib-1.20.1, and Pehkui-1.20.1 in my mods folder. I have tried playing with Fabric and Quilt respectively but still the same error.

**Comment by AmyMialee** [comment]
could you give the crash report? I need the whole thing

**Comment by altek3** [comment]
> could you give the crash report? I need the whole thing

[crash-2023-10-13_22.11.09-server.txt](https://github.com/AmyMialeeCommissions/annoyingdifficulty/files/12897790/crash-2023-10-13_22.11.09-server.txt)

there you go

**Comment by AmyMialee** [comment]
you have the forge version of pehkui, you need the fabric one
