### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by JeAtenis** [AmyMialeeCommissions/annoyingdifficulty#11]
![Captura de pantalla 2023-10-13 151135](https://github.com/AmyMialeeCommissions/annoyingdifficulty/assets/147873469/9b611713-d5c3-4c4d-bdf3-80a416a34109)
I open a new world over and over, try to see what is wrong, and nothing ;-; also the annoying mod isn't in the mods section, but i made sure to place the mod in the mods folder, is it normal for it to not appear?
and also is my first time using mods- i saw a tutoral in how to do it, and did everything as the guide said, everything was alright, except for this, the mod's doesn't work, doesn't do anything at all- tho i was testing in creative at first, and some small ammount of eyes of ender did break, but there was no shatter pieces.

**Comment by AmyMialee** [comment]
this is a fabric mod, not forge
