### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by JeAtenis** [AmyMialeeCommissions/annoyingdifficulty#12]
I was in creative, testing the mod, i grabbed the netherite shield, and my game crashed. I that normal? or a bug? same happened grabbing the egg of the fox in a desk. and it doesn't let me open the world, it crashes instantly when trying to go back again.
And the shard of the eye crashed my game too- ;-;
Alright, i made a survival mode, was punching a tree, got the mini game after punching a tree, crashed.
the code error is -1.

**Comment by AmyMialee** [comment]
need a crash log

**Comment by JeAtenis** [comment]
i already fixed it :,D
