### ISSUE TITLE
No text on menu

### ISSUE THREAD

**Issue by Kshtij-7** [AmyMialeeCommissions/annoyingdifficulty#15]
![image](https://github.com/AmyMialeeCommissions/annoyingdifficulty/assets/78255433/acb74631-18d0-490d-9ce2-c4e71eed84ba)
There is no text on menu on starting with optifine

**Comment by Simiea** [comment]
maybe it is annoying like that lol

**Comment by AmyMialee** [comment]
optifine isn't allowed and isn't going to be supported
use sodium or smth
