### ISSUE TITLE
Crashreport

### ISSUE THREAD

**Issue by joshuax8** [AmyMialeeCommissions/annoyingdifficulty#16]
Game crashed while I fell off of a ledge right when I was supposed to take fall damage, see crash report attached. Let me know if you need more info!

[crash-2023-10-14_20.30.51-client.txt](https://github.com/AmyMialeeCommissions/annoyingdifficulty/files/12907440/crash-2023-10-14_20.30.51-client.txt)

**Comment by AmyMialee** [comment]
should be fixed next update
