### ISSUE TITLE
Game crashed when I punched a fish

### ISSUE THREAD

**Issue by DatapackMaster** [AmyMialeeCommissions/annoyingdifficulty#17]
Pretty self explanatory. I punched a cod and BOOM game crash. The crash report is attached. If you need any more info, let me know!

PS: Great job on the mod!

[crash-2023-10-15_19.17.41-client.txt](https://github.com/AmyMialeeCommissions/annoyingdifficulty/files/12910060/crash-2023-10-15_19.17.41-client.txt)

**Comment by AmyMialee** [comment]
wasn't the fish! but yeah fixed in next update
