### ISSUE TITLE
Game crash when breaking a block

### ISSUE THREAD

**Issue by DatapackMaster** [AmyMialeeCommissions/annoyingdifficulty#18]
I broke stone and the game crashed. Note that I previously broke more pieces of stone with no problems.

[crash-2023-10-15_19.45.59-client.txt](https://github.com/AmyMialeeCommissions/annoyingdifficulty/files/12910149/crash-2023-10-15_19.45.59-client.txt)

**Comment by AmyMialee** [comment]
should be fixed next update
