### ISSUE TITLE
unskippable ad is accelerated

### ISSUE THREAD

**Issue by JustParanoia** [AmyMialeeCommissions/annoyingdifficulty#19]
unskippable ad runs instead of 30 seconds, more like 6 seconds

https://github.com/AmyMialeeCommissions/annoyingdifficulty/assets/148149939/4445bced-b1b9-4f08-8b22-54bb370e9e8c

**Comment by AmyMialee** [comment]
yeah I think it's FPS dependent for some reason

**Comment by JustParanoia** [comment]
> yeah I think it's FPS dependent for some reason

Yeah you're right, anything above 60 fps is faster than normal
Thanks
