### ISSUE TITLE
Doesn't seem to work.

### ISSUE THREAD

**Issue by BashyBush** [AmyMialeeCommissions/annoyingdifficulty#3]
I don't know what im doing wrong but when I have the required mods on, open minecraft and load into a singleplayer world. Nothing happens. uh?
![image](https://github.com/AmyMialeeCommissions/annoyingdifficulty/assets/84814202/4990e8d2-06e4-49c1-b8fc-ee029cecd376)

**Comment by AmyMialee** [comment]
do you have fabric loader?

**Comment by AmyMialee** [comment]
like try do this with another fabric mod loaded to see if they both fail or if it's this mod's issue

**Comment by BashyBush** [comment]
nvm it got it working now. :v
