### ISSUE TITLE
While fixing my leg from "touching grass", I still get tped regarding the quest master. Which ends up resulting in me dying.

### ISSUE THREAD

**Issue by neamm** [AmyMialeeCommissions/annoyingdifficulty#9]
![image](https://github.com/AmyMialeeCommissions/annoyingdifficulty/assets/146665856/8c84ca6d-7ad6-4123-8f37-520a0eaed955)
![image](https://github.com/AmyMialeeCommissions/annoyingdifficulty/assets/146665856/30c4d815-7295-482a-8fb2-76e924713f1c)

**Comment by neamm** [comment]
oops wrong image. 
![image](https://github.com/AmyMialeeCommissions/annoyingdifficulty/assets/146665856/ee7a7439-0ad0-48ef-b41d-39956c170aa9)

**Comment by AmyMialee** [comment]
intended
